// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredAdminLoginFailures = `-- name: DeleteExpiredAdminLoginFailures :exec
DELETE FROM admin_login_failures WHERE reset_at < now()
`

func (q *Queries) DeleteExpiredAdminLoginFailures(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAdminLoginFailures)
	return err
}

const deleteExpiredAdminSessions = `-- name: DeleteExpiredAdminSessions :exec
DELETE FROM admin_sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredAdminSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAdminSessions)
	return err
}

const deleteExpiredSessionBindings = `-- name: DeleteExpiredSessionBindings :exec
DELETE FROM session_bindings WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessionBindings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessionBindings)
	return err
}

const deleteExpiredUsageDedup = `-- name: DeleteExpiredUsageDedup :execrows
WITH expired AS (
    SELECT usage_event_dedup.api_key_id, usage_event_dedup.event_hash
    FROM usage_event_dedup
    WHERE usage_event_dedup.created_at < $1
    ORDER BY usage_event_dedup.created_at
    LIMIT $2
)
DELETE FROM usage_event_dedup target
USING expired
WHERE target.api_key_id = expired.api_key_id
  AND target.event_hash = expired.event_hash
`

type DeleteExpiredUsageDedupParams struct {
	Cutoff     pgtype.Timestamptz
	BatchLimit int32
}

func (q *Queries) DeleteExpiredUsageDedup(ctx context.Context, arg DeleteExpiredUsageDedupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredUsageDedup, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
