// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: migrations.sql

package storedb

import (
	"context"
)

const ensureSchemaMigrations = `-- name: EnsureSchemaMigrations :exec
CREATE TABLE IF NOT EXISTS schema_migrations (
    version text PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
)
`

func (q *Queries) EnsureSchemaMigrations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ensureSchemaMigrations)
	return err
}

const lockMigrations = `-- name: LockMigrations :exec
SELECT pg_advisory_xact_lock(731242001)
`

func (q *Queries) LockMigrations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockMigrations)
	return err
}

const migrationApplied = `-- name: MigrationApplied :one
SELECT EXISTS (
    SELECT 1 FROM schema_migrations WHERE version = $1
)
`

func (q *Queries) MigrationApplied(ctx context.Context, version string) (bool, error) {
	row := q.db.QueryRow(ctx, migrationApplied, version)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordMigration = `-- name: RecordMigration :exec
INSERT INTO schema_migrations(version)
VALUES ($1)
ON CONFLICT DO NOTHING
`

func (q *Queries) RecordMigration(ctx context.Context, version string) error {
	_, err := q.db.Exec(ctx, recordMigration, version)
	return err
}
