// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminLoginFailure struct {
	ScopeKey     string
	FailureCount int32
	ResetAt      pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AdminSession struct {
	SessionHash []byte
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type ApiKey struct {
	ID         string
	PoolID     string
	KeyHmac    []byte
	KeyHint    string
	Scopes     []string
	RateLimit  int32
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	EmployeeID string
}

type ApiKeyAccountBinding struct {
	ApiKeyID          string
	ProviderAccountID string
	AssignedAt        pgtype.Timestamptz
}

type ApiKeyRateLimit struct {
	ApiKeyID     string
	WindowStart  pgtype.Timestamptz
	RequestCount int32
}

type ApiKeyUsageDaily struct {
	ApiKeyID     string
	UsageDate    pgtype.Date
	InputTokens  int64
	OutputTokens int64
	UpdatedAt    pgtype.Timestamptz
	Model        string
}

type AuditEvent struct {
	ID         int64
	Actor      string
	Action     string
	TargetType string
	TargetID   string
	Result     string
	CreatedAt  pgtype.Timestamptz
}

type Employee struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type GlobalSetting struct {
	Singleton            bool
	MaxApiKeysPerAccount int32
	UpdatedAt            pgtype.Timestamptz
}

type Pool struct {
	ID        string
	Name      string
	Provider  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type PoolAccount struct {
	PoolID            string
	ProviderAccountID string
	Weight            int32
	Priority          int32
	Enabled           bool
}

type ProviderAccount struct {
	ID                              string
	Provider                        string
	CredentialType                  string
	DisplayName                     string
	SubjectHmac                     []byte
	CredentialCiphertext            []byte
	CredentialVersion               int32
	Status                          string
	QuotaSnapshot                   []byte
	CooldownUntil                   pgtype.Timestamptz
	LastSuccessAt                   pgtype.Timestamptz
	LastFailureAt                   pgtype.Timestamptz
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
	HealthStatus                    string
	LastCheckedAt                   pgtype.Timestamptz
	LastHealthErrorCode             *string
	ConsecutiveHealthFailures       int32
	NextHealthCheckAt               pgtype.Timestamptz
	Email                           *string
	ResetCreditsSnapshot            []byte
	ResetCreditsCheckedAt           pgtype.Timestamptz
	ResetCreditsRefreshClaimedUntil pgtype.Timestamptz
	FastModeEnabled                 bool
	QuotaCheckedAt                  pgtype.Timestamptz
	LastQuotaErrorCode              *string
}

type SchemaMigration struct {
	Version   string
	AppliedAt pgtype.Timestamptz
}

type SessionBinding struct {
	ApiKeyID          string
	PoolID            string
	SessionHash       []byte
	ProviderAccountID string
	ExpiresAt         pgtype.Timestamptz
}

type UsageEventDedup struct {
	ApiKeyID  string
	EventHash []byte
	CreatedAt pgtype.Timestamptz
}
