// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimProviderHealthChecks = `-- name: ClaimProviderHealthChecks :many
WITH due AS (
    SELECT candidate.id FROM provider_accounts candidate
    WHERE (candidate.status IN ('active', 'exhausted') AND (candidate.next_health_check_at IS NULL OR candidate.next_health_check_at <= $2))
       OR (candidate.status = 'cooling_down' AND candidate.cooldown_until <= $2)
    ORDER BY candidate.next_health_check_at NULLS FIRST, candidate.id
    FOR UPDATE SKIP LOCKED
    LIMIT $3
)
UPDATE provider_accounts a
SET next_health_check_at = $1, updated_at = now()
FROM due
WHERE a.id = due.id
RETURNING a.id, a.provider, a.credential_type, a.display_name, a.credential_ciphertext,
    a.credential_version, a.status, a.health_status, a.last_checked_at,
    COALESCE(a.last_health_error_code, '') AS last_health_error_code,
    a.consecutive_health_failures, a.next_health_check_at
`

type ClaimProviderHealthChecksParams struct {
	ClaimedUntil pgtype.Timestamptz
	Now          pgtype.Timestamptz
	ClaimLimit   int32
}

type ClaimProviderHealthChecksRow struct {
	ID                        string
	Provider                  string
	CredentialType            string
	DisplayName               string
	CredentialCiphertext      []byte
	CredentialVersion         int32
	Status                    string
	HealthStatus              string
	LastCheckedAt             pgtype.Timestamptz
	LastHealthErrorCode       string
	ConsecutiveHealthFailures int32
	NextHealthCheckAt         pgtype.Timestamptz
}

func (q *Queries) ClaimProviderHealthChecks(ctx context.Context, arg ClaimProviderHealthChecksParams) ([]ClaimProviderHealthChecksRow, error) {
	rows, err := q.db.Query(ctx, claimProviderHealthChecks, arg.ClaimedUntil, arg.Now, arg.ClaimLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimProviderHealthChecksRow
	for rows.Next() {
		var i ClaimProviderHealthChecksRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.CredentialType,
			&i.DisplayName,
			&i.CredentialCiphertext,
			&i.CredentialVersion,
			&i.Status,
			&i.HealthStatus,
			&i.LastCheckedAt,
			&i.LastHealthErrorCode,
			&i.ConsecutiveHealthFailures,
			&i.NextHealthCheckAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimProviderResetCreditRefresh = `-- name: ClaimProviderResetCreditRefresh :execrows
UPDATE provider_accounts SET reset_credits_refresh_claimed_until = $1
WHERE id = $2
  AND (reset_credits_checked_at IS NULL OR reset_credits_checked_at < $3)
  AND (reset_credits_refresh_claimed_until IS NULL OR reset_credits_refresh_claimed_until < now())
`

type ClaimProviderResetCreditRefreshParams struct {
	ClaimedUntil pgtype.Timestamptz
	ID           string
	StaleBefore  pgtype.Timestamptz
}

func (q *Queries) ClaimProviderResetCreditRefresh(ctx context.Context, arg ClaimProviderResetCreditRefreshParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimProviderResetCreditRefresh, arg.ClaimedUntil, arg.ID, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createProviderAccount = `-- name: CreateProviderAccount :exec
INSERT INTO provider_accounts (
    id, provider, credential_type, display_name, email, subject_hmac,
    credential_ciphertext, credential_version, status, quota_snapshot,
    quota_checked_at, last_quota_error_code, health_status, last_checked_at,
    last_health_error_code, consecutive_health_failures, next_health_check_at
) VALUES (
    $1, $2, $3, $4,
    NULLIF($5::text, ''), $6, $7,
    $8, $9, $10,
    $11, NULLIF($12::text, ''),
    COALESCE(NULLIF($13::text, ''), 'unknown'), $14,
    NULLIF($15::text, ''), $16,
    $17
)
`

type CreateProviderAccountParams struct {
	ID                        string
	Provider                  string
	CredentialType            string
	DisplayName               string
	Email                     string
	SubjectHmac               []byte
	CredentialCiphertext      []byte
	CredentialVersion         int32
	Status                    string
	QuotaSnapshot             []byte
	QuotaCheckedAt            pgtype.Timestamptz
	LastQuotaErrorCode        string
	HealthStatus              string
	LastCheckedAt             pgtype.Timestamptz
	LastHealthErrorCode       string
	ConsecutiveHealthFailures int32
	NextHealthCheckAt         pgtype.Timestamptz
}

func (q *Queries) CreateProviderAccount(ctx context.Context, arg CreateProviderAccountParams) error {
	_, err := q.db.Exec(ctx, createProviderAccount,
		arg.ID,
		arg.Provider,
		arg.CredentialType,
		arg.DisplayName,
		arg.Email,
		arg.SubjectHmac,
		arg.CredentialCiphertext,
		arg.CredentialVersion,
		arg.Status,
		arg.QuotaSnapshot,
		arg.QuotaCheckedAt,
		arg.LastQuotaErrorCode,
		arg.HealthStatus,
		arg.LastCheckedAt,
		arg.LastHealthErrorCode,
		arg.ConsecutiveHealthFailures,
		arg.NextHealthCheckAt,
	)
	return err
}

const deleteProviderAccount = `-- name: DeleteProviderAccount :execrows
DELETE FROM provider_accounts a
WHERE a.id = $1
  AND NOT EXISTS (
      SELECT 1 FROM api_key_account_bindings b
      JOIN api_keys k ON k.id = b.api_key_id
      WHERE b.provider_account_id = a.id
        AND k.revoked_at IS NULL
        AND (k.expires_at IS NULL OR k.expires_at > now())
  )
`

func (q *Queries) DeleteProviderAccount(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProviderAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProviderAccount = `-- name: GetProviderAccount :one
SELECT
    id, provider, credential_type, display_name, COALESCE(email, '') AS email,
    credential_ciphertext, credential_version, status, fast_mode_enabled,
    quota_snapshot, quota_checked_at, COALESCE(last_quota_error_code, '') AS last_quota_error_code,
    cooldown_until, last_success_at, last_failure_at, health_status, last_checked_at,
    COALESCE(last_health_error_code, '') AS last_health_error_code,
    consecutive_health_failures, next_health_check_at, created_at, updated_at
FROM provider_accounts
WHERE id = $1
`

type GetProviderAccountRow struct {
	ID                        string
	Provider                  string
	CredentialType            string
	DisplayName               string
	Email                     string
	CredentialCiphertext      []byte
	CredentialVersion         int32
	Status                    string
	FastModeEnabled           bool
	QuotaSnapshot             []byte
	QuotaCheckedAt            pgtype.Timestamptz
	LastQuotaErrorCode        string
	CooldownUntil             pgtype.Timestamptz
	LastSuccessAt             pgtype.Timestamptz
	LastFailureAt             pgtype.Timestamptz
	HealthStatus              string
	LastCheckedAt             pgtype.Timestamptz
	LastHealthErrorCode       string
	ConsecutiveHealthFailures int32
	NextHealthCheckAt         pgtype.Timestamptz
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

func (q *Queries) GetProviderAccount(ctx context.Context, id string) (GetProviderAccountRow, error) {
	row := q.db.QueryRow(ctx, getProviderAccount, id)
	var i GetProviderAccountRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.CredentialType,
		&i.DisplayName,
		&i.Email,
		&i.CredentialCiphertext,
		&i.CredentialVersion,
		&i.Status,
		&i.FastModeEnabled,
		&i.QuotaSnapshot,
		&i.QuotaCheckedAt,
		&i.LastQuotaErrorCode,
		&i.CooldownUntil,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.HealthStatus,
		&i.LastCheckedAt,
		&i.LastHealthErrorCode,
		&i.ConsecutiveHealthFailures,
		&i.NextHealthCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderResetCredits = `-- name: GetProviderResetCredits :one
SELECT reset_credits_snapshot, reset_credits_checked_at
FROM provider_accounts
WHERE id = $1
`

type GetProviderResetCreditsRow struct {
	ResetCreditsSnapshot  []byte
	ResetCreditsCheckedAt pgtype.Timestamptz
}

func (q *Queries) GetProviderResetCredits(ctx context.Context, id string) (GetProviderResetCreditsRow, error) {
	row := q.db.QueryRow(ctx, getProviderResetCredits, id)
	var i GetProviderResetCreditsRow
	err := row.Scan(&i.ResetCreditsSnapshot, &i.ResetCreditsCheckedAt)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT max_api_keys_per_account, updated_at
FROM global_settings
WHERE singleton
`

type GetSettingsRow struct {
	MaxApiKeysPerAccount int32
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) GetSettings(ctx context.Context) (GetSettingsRow, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i GetSettingsRow
	err := row.Scan(&i.MaxApiKeysPerAccount, &i.UpdatedAt)
	return i, err
}

const listPoolProviderAccounts = `-- name: ListPoolProviderAccounts :many
SELECT
    a.id, a.provider, a.credential_type, a.display_name, COALESCE(a.email, '') AS email,
    a.credential_ciphertext, a.credential_version, a.status, a.fast_mode_enabled,
    a.health_status, a.quota_snapshot, a.cooldown_until, a.last_success_at,
    a.last_failure_at, a.created_at, a.updated_at
FROM provider_accounts a
JOIN pool_accounts pa ON pa.provider_account_id = a.id
WHERE pa.pool_id = $1
  AND pa.enabled
  AND (a.status = 'active' OR (a.status = 'cooling_down' AND a.cooldown_until <= now()))
  AND COALESCE(NULLIF(a.health_status, ''), 'unknown') != 'unhealthy'
ORDER BY pa.priority, a.id
`

type ListPoolProviderAccountsRow struct {
	ID                   string
	Provider             string
	CredentialType       string
	DisplayName          string
	Email                string
	CredentialCiphertext []byte
	CredentialVersion    int32
	Status               string
	FastModeEnabled      bool
	HealthStatus         string
	QuotaSnapshot        []byte
	CooldownUntil        pgtype.Timestamptz
	LastSuccessAt        pgtype.Timestamptz
	LastFailureAt        pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) ListPoolProviderAccounts(ctx context.Context, poolID string) ([]ListPoolProviderAccountsRow, error) {
	rows, err := q.db.Query(ctx, listPoolProviderAccounts, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoolProviderAccountsRow
	for rows.Next() {
		var i ListPoolProviderAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.CredentialType,
			&i.DisplayName,
			&i.Email,
			&i.CredentialCiphertext,
			&i.CredentialVersion,
			&i.Status,
			&i.FastModeEnabled,
			&i.HealthStatus,
			&i.QuotaSnapshot,
			&i.CooldownUntil,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderAccounts = `-- name: ListProviderAccounts :many
SELECT
    a.id, a.provider, a.credential_type, a.display_name, COALESCE(a.email, '') AS email,
    a.credential_version, a.status, a.fast_mode_enabled,
    (SELECT count(*) FROM api_key_account_bindings b
        JOIN api_keys k ON k.id = b.api_key_id
        WHERE b.provider_account_id = a.id
          AND k.revoked_at IS NULL
          AND (k.expires_at IS NULL OR k.expires_at > now())) AS assigned_api_keys,
    a.quota_snapshot, a.quota_checked_at, COALESCE(a.last_quota_error_code, '') AS last_quota_error_code,
    a.cooldown_until, a.last_success_at, a.last_failure_at, a.health_status, a.last_checked_at,
    COALESCE(a.last_health_error_code, '') AS last_health_error_code,
    a.consecutive_health_failures, a.next_health_check_at, a.created_at, a.updated_at
FROM provider_accounts a
ORDER BY a.created_at
`

type ListProviderAccountsRow struct {
	ID                        string
	Provider                  string
	CredentialType            string
	DisplayName               string
	Email                     string
	CredentialVersion         int32
	Status                    string
	FastModeEnabled           bool
	AssignedApiKeys           int64
	QuotaSnapshot             []byte
	QuotaCheckedAt            pgtype.Timestamptz
	LastQuotaErrorCode        string
	CooldownUntil             pgtype.Timestamptz
	LastSuccessAt             pgtype.Timestamptz
	LastFailureAt             pgtype.Timestamptz
	HealthStatus              string
	LastCheckedAt             pgtype.Timestamptz
	LastHealthErrorCode       string
	ConsecutiveHealthFailures int32
	NextHealthCheckAt         pgtype.Timestamptz
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

func (q *Queries) ListProviderAccounts(ctx context.Context) ([]ListProviderAccountsRow, error) {
	rows, err := q.db.Query(ctx, listProviderAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderAccountsRow
	for rows.Next() {
		var i ListProviderAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.CredentialType,
			&i.DisplayName,
			&i.Email,
			&i.CredentialVersion,
			&i.Status,
			&i.FastModeEnabled,
			&i.AssignedApiKeys,
			&i.QuotaSnapshot,
			&i.QuotaCheckedAt,
			&i.LastQuotaErrorCode,
			&i.CooldownUntil,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.HealthStatus,
			&i.LastCheckedAt,
			&i.LastHealthErrorCode,
			&i.ConsecutiveHealthFailures,
			&i.NextHealthCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProviderAccountForDeletion = `-- name: LockProviderAccountForDeletion :one
SELECT id FROM provider_accounts WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockProviderAccountForDeletion(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockProviderAccountForDeletion, id)
	err := row.Scan(&id)
	return id, err
}

const reactivateProviderIfCooldownExpired = `-- name: ReactivateProviderIfCooldownExpired :execrows
UPDATE provider_accounts SET status = 'active', cooldown_until = NULL, updated_at = now()
WHERE id = $1
  AND status = 'cooling_down'
  AND cooldown_until <= $2
`

type ReactivateProviderIfCooldownExpiredParams struct {
	ID  string
	Now pgtype.Timestamptz
}

func (q *Queries) ReactivateProviderIfCooldownExpired(ctx context.Context, arg ReactivateProviderIfCooldownExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, reactivateProviderIfCooldownExpired, arg.ID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordProviderHealthFailure = `-- name: RecordProviderHealthFailure :execrows
UPDATE provider_accounts SET
    consecutive_health_failures = consecutive_health_failures + 1,
    health_status = CASE WHEN consecutive_health_failures + 1 >= 3 THEN 'unhealthy' ELSE health_status END,
    last_checked_at = $1,
    last_health_error_code = $2,
    next_health_check_at = $3,
    updated_at = now()
WHERE id = $4
`

type RecordProviderHealthFailureParams struct {
	CheckedAt   pgtype.Timestamptz
	ErrorCode   *string
	NextCheckAt pgtype.Timestamptz
	ID          string
}

func (q *Queries) RecordProviderHealthFailure(ctx context.Context, arg RecordProviderHealthFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordProviderHealthFailure,
		arg.CheckedAt,
		arg.ErrorCode,
		arg.NextCheckAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseProviderResetCreditRefresh = `-- name: ReleaseProviderResetCreditRefresh :execrows
UPDATE provider_accounts
SET reset_credits_refresh_claimed_until = NULL
WHERE id = $1
`

func (q *Queries) ReleaseProviderResetCreditRefresh(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, releaseProviderResetCreditRefresh, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProviderHealth = `-- name: SetProviderHealth :execrows
UPDATE provider_accounts SET
    health_status = $1,
    last_checked_at = $2,
    last_health_error_code = NULLIF($3::text, ''),
    consecutive_health_failures = CASE WHEN $1 IN ('healthy', 'unknown') THEN 0 ELSE consecutive_health_failures END,
    next_health_check_at = $4,
    updated_at = now()
WHERE id = $5
`

type SetProviderHealthParams struct {
	HealthStatus string
	CheckedAt    pgtype.Timestamptz
	ErrorCode    string
	NextCheckAt  pgtype.Timestamptz
	ID           string
}

func (q *Queries) SetProviderHealth(ctx context.Context, arg SetProviderHealthParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProviderHealth,
		arg.HealthStatus,
		arg.CheckedAt,
		arg.ErrorCode,
		arg.NextCheckAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProviderQuotaError = `-- name: SetProviderQuotaError :execrows
UPDATE provider_accounts SET
    last_quota_error_code = NULLIF($1::text, ''),
    next_health_check_at = $2,
    updated_at = now()
WHERE id = $3
`

type SetProviderQuotaErrorParams struct {
	ErrorCode   string
	NextCheckAt pgtype.Timestamptz
	ID          string
}

func (q *Queries) SetProviderQuotaError(ctx context.Context, arg SetProviderQuotaErrorParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProviderQuotaError, arg.ErrorCode, arg.NextCheckAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProviderResetCredits = `-- name: SetProviderResetCredits :execrows
UPDATE provider_accounts SET
    reset_credits_snapshot = $1,
    reset_credits_checked_at = $2,
    reset_credits_refresh_claimed_until = NULL,
    updated_at = now()
WHERE id = $3
`

type SetProviderResetCreditsParams struct {
	Snapshot  []byte
	CheckedAt pgtype.Timestamptz
	ID        string
}

func (q *Queries) SetProviderResetCredits(ctx context.Context, arg SetProviderResetCreditsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProviderResetCredits, arg.Snapshot, arg.CheckedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProviderUsageAllowed = `-- name: SetProviderUsageAllowed :execrows
UPDATE provider_accounts SET
    status = CASE
        WHEN $1::boolean AND status = 'exhausted' THEN 'active'
        WHEN NOT $1::boolean AND status IN ('active', 'cooling_down', 'exhausted') THEN 'exhausted'
        ELSE status
    END,
    cooldown_until = CASE
        WHEN ($1::boolean AND status = 'exhausted')
          OR (NOT $1::boolean AND status IN ('active', 'cooling_down', 'exhausted')) THEN NULL
        ELSE cooldown_until
    END,
    updated_at = now()
WHERE id = $2
`

type SetProviderUsageAllowedParams struct {
	Allowed bool
	ID      string
}

func (q *Queries) SetProviderUsageAllowed(ctx context.Context, arg SetProviderUsageAllowedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProviderUsageAllowed, arg.Allowed, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProviderAccount = `-- name: UpdateProviderAccount :execrows
UPDATE provider_accounts SET
    display_name = COALESCE($1, display_name),
    status = COALESCE($2, status),
    fast_mode_enabled = COALESCE($3, fast_mode_enabled),
    cooldown_until = CASE WHEN $2 = 'active' THEN NULL ELSE cooldown_until END,
    updated_at = now()
WHERE id = $4
`

type UpdateProviderAccountParams struct {
	DisplayName     *string
	Status          *string
	FastModeEnabled *bool
	ID              string
}

func (q *Queries) UpdateProviderAccount(ctx context.Context, arg UpdateProviderAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProviderAccount,
		arg.DisplayName,
		arg.Status,
		arg.FastModeEnabled,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProviderCredentialCAS = `-- name: UpdateProviderCredentialCAS :execrows
UPDATE provider_accounts SET
    credential_ciphertext = $1,
    credential_version = $2,
    status = CASE WHEN status IN ('disabled', 'exhausted') THEN status ELSE 'active' END,
    cooldown_until = CASE WHEN status IN ('disabled', 'exhausted') THEN cooldown_until ELSE NULL END,
    updated_at = now()
WHERE id = $3 AND credential_version = $4
`

type UpdateProviderCredentialCASParams struct {
	CredentialCiphertext []byte
	CredentialVersion    int32
	ID                   string
	ExpectedVersion      int32
}

func (q *Queries) UpdateProviderCredentialCAS(ctx context.Context, arg UpdateProviderCredentialCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProviderCredentialCAS,
		arg.CredentialCiphertext,
		arg.CredentialVersion,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProviderDetailsWithQuota = `-- name: UpdateProviderDetailsWithQuota :execrows
UPDATE provider_accounts SET
    email = COALESCE(NULLIF($1::text, ''), email),
    quota_snapshot = $2,
    quota_checked_at = $3,
    last_quota_error_code = NULL,
    updated_at = now()
WHERE id = $4
`

type UpdateProviderDetailsWithQuotaParams struct {
	Email          string
	QuotaSnapshot  []byte
	QuotaCheckedAt pgtype.Timestamptz
	ID             string
}

func (q *Queries) UpdateProviderDetailsWithQuota(ctx context.Context, arg UpdateProviderDetailsWithQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProviderDetailsWithQuota,
		arg.Email,
		arg.QuotaSnapshot,
		arg.QuotaCheckedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProviderEmail = `-- name: UpdateProviderEmail :execrows
UPDATE provider_accounts SET
    email = COALESCE(NULLIF($1::text, ''), email),
    updated_at = now()
WHERE id = $2
`

type UpdateProviderEmailParams struct {
	Email string
	ID    string
}

func (q *Queries) UpdateProviderEmail(ctx context.Context, arg UpdateProviderEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProviderEmail, arg.Email, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProviderStatus = `-- name: UpdateProviderStatus :execrows
UPDATE provider_accounts SET
    status = $1,
    cooldown_until = $2,
    last_failure_at = CASE WHEN $1 = 'active' THEN last_failure_at ELSE now() END,
    health_status = CASE WHEN $1 = 'auth_failed' THEN 'unhealthy' WHEN $1 = 'cooling_down' THEN 'healthy' ELSE health_status END,
    last_checked_at = CASE WHEN $1 IN ('auth_failed', 'cooling_down') THEN now() ELSE last_checked_at END,
    last_health_error_code = CASE WHEN $1 = 'auth_failed' THEN 'authentication_failed' WHEN $1 = 'cooling_down' THEN NULL ELSE last_health_error_code END,
    consecutive_health_failures = CASE WHEN $1 = 'auth_failed' THEN 3 WHEN $1 = 'cooling_down' THEN 0 ELSE consecutive_health_failures END,
    next_health_check_at = CASE WHEN $1 IN ('auth_failed', 'cooling_down') THEN now() + interval '5 minutes' ELSE next_health_check_at END,
    updated_at = now()
WHERE id = $3
`

type UpdateProviderStatusParams struct {
	Status        string
	CooldownUntil pgtype.Timestamptz
	ID            string
}

func (q *Queries) UpdateProviderStatus(ctx context.Context, arg UpdateProviderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProviderStatus, arg.Status, arg.CooldownUntil, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSettings = `-- name: UpdateSettings :execrows
UPDATE global_settings
SET max_api_keys_per_account = $1, updated_at = now()
WHERE singleton
`

func (q *Queries) UpdateSettings(ctx context.Context, maxApiKeysPerAccount int32) (int64, error) {
	result, err := q.db.Exec(ctx, updateSettings, maxApiKeysPerAccount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
