// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routing.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addInitialPoolAccount = `-- name: AddInitialPoolAccount :execrows
INSERT INTO pool_accounts(pool_id, provider_account_id, weight, priority, enabled)
SELECT $1, $2, $3, $4, $5
FROM provider_accounts a
WHERE a.id = $2
`

type AddInitialPoolAccountParams struct {
	PoolID            string
	ProviderAccountID string
	Weight            int32
	Priority          int32
	Enabled           bool
}

func (q *Queries) AddInitialPoolAccount(ctx context.Context, arg AddInitialPoolAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, addInitialPoolAccount,
		arg.PoolID,
		arg.ProviderAccountID,
		arg.Weight,
		arg.Priority,
		arg.Enabled,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addUsage = `-- name: AddUsage :exec
INSERT INTO api_key_usage_daily(api_key_id, usage_date, model, input_tokens, output_tokens)
VALUES ($1, $2, $3,
    $4, $5)
ON CONFLICT(api_key_id, usage_date, model) DO UPDATE SET
    input_tokens = api_key_usage_daily.input_tokens + excluded.input_tokens,
    output_tokens = api_key_usage_daily.output_tokens + excluded.output_tokens,
    updated_at = now()
`

type AddUsageParams struct {
	ApiKeyID     string
	UsageDate    pgtype.Date
	Model        string
	InputTokens  int64
	OutputTokens int64
}

func (q *Queries) AddUsage(ctx context.Context, arg AddUsageParams) error {
	_, err := q.db.Exec(ctx, addUsage,
		arg.ApiKeyID,
		arg.UsageDate,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
	)
	return err
}

const bindAPIKey = `-- name: BindAPIKey :exec
INSERT INTO api_key_account_bindings(api_key_id, provider_account_id)
VALUES ($1, $2)
`

type BindAPIKeyParams struct {
	ApiKeyID          string
	ProviderAccountID string
}

func (q *Queries) BindAPIKey(ctx context.Context, arg BindAPIKeyParams) error {
	_, err := q.db.Exec(ctx, bindAPIKey, arg.ApiKeyID, arg.ProviderAccountID)
	return err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys(id, pool_id, employee_name, key_hmac, key_hint, scopes, rate_limit, expires_at)
VALUES ($1, $2, $3, $4,
    $5, $6, $7, $8)
`

type CreateAPIKeyParams struct {
	ID           string
	PoolID       string
	EmployeeName string
	KeyHmac      []byte
	KeyHint      string
	Scopes       []string
	RateLimit    int32
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.PoolID,
		arg.EmployeeName,
		arg.KeyHmac,
		arg.KeyHint,
		arg.Scopes,
		arg.RateLimit,
		arg.ExpiresAt,
	)
	return err
}

const createPool = `-- name: CreatePool :exec
INSERT INTO pools(id, name, provider)
VALUES ($1, $2, $3)
`

type CreatePoolParams struct {
	ID       string
	Name     string
	Provider string
}

func (q *Queries) CreatePool(ctx context.Context, arg CreatePoolParams) error {
	_, err := q.db.Exec(ctx, createPool, arg.ID, arg.Name, arg.Provider)
	return err
}

const deduplicateUsageEvent = `-- name: DeduplicateUsageEvent :execrows
INSERT INTO usage_event_dedup(api_key_id, event_hash)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type DeduplicateUsageEventParams struct {
	ApiKeyID  string
	EventHash []byte
}

func (q *Queries) DeduplicateUsageEvent(ctx context.Context, arg DeduplicateUsageEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, deduplicateUsageEvent, arg.ApiKeyID, arg.EventHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProviderAccountProvider = `-- name: GetProviderAccountProvider :one
SELECT provider FROM provider_accounts WHERE id = $1
`

func (q *Queries) GetProviderAccountProvider(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getProviderAccountProvider, id)
	var provider string
	err := row.Scan(&provider)
	return provider, err
}

const getRoutableProviderAccount = `-- name: GetRoutableProviderAccount :one
SELECT id, provider, credential_type, display_name, credential_ciphertext,
    credential_version, status, fast_mode_enabled, health_status, quota_snapshot,
    cooldown_until, last_success_at, last_failure_at, created_at, updated_at
FROM provider_accounts
WHERE id = $1
`

type GetRoutableProviderAccountRow struct {
	ID                   string
	Provider             string
	CredentialType       string
	DisplayName          string
	CredentialCiphertext []byte
	CredentialVersion    int32
	Status               string
	FastModeEnabled      bool
	HealthStatus         string
	QuotaSnapshot        []byte
	CooldownUntil        pgtype.Timestamptz
	LastSuccessAt        pgtype.Timestamptz
	LastFailureAt        pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) GetRoutableProviderAccount(ctx context.Context, id string) (GetRoutableProviderAccountRow, error) {
	row := q.db.QueryRow(ctx, getRoutableProviderAccount, id)
	var i GetRoutableProviderAccountRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.CredentialType,
		&i.DisplayName,
		&i.CredentialCiphertext,
		&i.CredentialVersion,
		&i.Status,
		&i.FastModeEnabled,
		&i.HealthStatus,
		&i.QuotaSnapshot,
		&i.CooldownUntil,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsageTotals = `-- name: GetUsageTotals :one
SELECT
    COALESCE(SUM(u.input_tokens), 0)::bigint AS input_tokens,
    COALESCE(SUM(u.output_tokens), 0)::bigint AS output_tokens
FROM api_key_usage_daily u
WHERE (NULLIF($1::text, '')::uuid IS NULL OR u.api_key_id = NULLIF($1::text, '')::uuid)
  AND ($2::timestamptz IS NULL OR u.usage_date >= $2::date)
  AND ($3::timestamptz IS NULL OR u.usage_date <= $3::date)
`

type GetUsageTotalsParams struct {
	ApiKeyID string
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type GetUsageTotalsRow struct {
	InputTokens  int64
	OutputTokens int64
}

func (q *Queries) GetUsageTotals(ctx context.Context, arg GetUsageTotalsParams) (GetUsageTotalsRow, error) {
	row := q.db.QueryRow(ctx, getUsageTotals, arg.ApiKeyID, arg.FromTime, arg.ToTime)
	var i GetUsageTotalsRow
	err := row.Scan(&i.InputTokens, &i.OutputTokens)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT k.id, k.pool_id, COALESCE(b.provider_account_id::text, '')::text AS provider_account_id,
    k.employee_name, k.key_hint, k.scopes, k.rate_limit, k.expires_at, k.revoked_at,
    k.last_used_at, k.created_at
FROM api_keys k
LEFT JOIN api_key_account_bindings b ON b.api_key_id = k.id
ORDER BY k.last_used_at DESC NULLS LAST, k.created_at DESC
`

type ListAPIKeysRow struct {
	ID                string
	PoolID            string
	ProviderAccountID string
	EmployeeName      string
	KeyHint           string
	Scopes            []string
	RateLimit         int32
	ExpiresAt         pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	LastUsedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysRow
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.ProviderAccountID,
			&i.EmployeeName,
			&i.KeyHint,
			&i.Scopes,
			&i.RateLimit,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolAccounts = `-- name: ListPoolAccounts :many
SELECT pool_id, provider_account_id, weight, priority, enabled
FROM pool_accounts
ORDER BY priority, provider_account_id
`

func (q *Queries) ListPoolAccounts(ctx context.Context) ([]PoolAccount, error) {
	rows, err := q.db.Query(ctx, listPoolAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoolAccount
	for rows.Next() {
		var i PoolAccount
		if err := rows.Scan(
			&i.PoolID,
			&i.ProviderAccountID,
			&i.Weight,
			&i.Priority,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPools = `-- name: ListPools :many
SELECT id, name, provider, created_at, updated_at
FROM pools
ORDER BY created_at
`

func (q *Queries) ListPools(ctx context.Context) ([]Pool, error) {
	rows, err := q.db.Query(ctx, listPools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pool
	for rows.Next() {
		var i Pool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopUsageKeys = `-- name: ListTopUsageKeys :many
SELECT u.api_key_id, k.employee_name, k.key_hint,
    SUM(u.input_tokens)::bigint AS input_tokens,
    SUM(u.output_tokens)::bigint AS output_tokens
FROM api_key_usage_daily u
JOIN api_keys k ON k.id = u.api_key_id
WHERE (NULLIF($1::text, '')::uuid IS NULL OR u.api_key_id = NULLIF($1::text, '')::uuid)
  AND ($2::timestamptz IS NULL OR u.usage_date >= $2::date)
  AND ($3::timestamptz IS NULL OR u.usage_date <= $3::date)
GROUP BY u.api_key_id, k.employee_name, k.key_hint
ORDER BY (SUM(u.input_tokens) + SUM(u.output_tokens)) DESC, u.api_key_id
LIMIT $4
`

type ListTopUsageKeysParams struct {
	ApiKeyID string
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
	TopLimit int32
}

type ListTopUsageKeysRow struct {
	ApiKeyID     string
	EmployeeName string
	KeyHint      string
	InputTokens  int64
	OutputTokens int64
}

func (q *Queries) ListTopUsageKeys(ctx context.Context, arg ListTopUsageKeysParams) ([]ListTopUsageKeysRow, error) {
	rows, err := q.db.Query(ctx, listTopUsageKeys,
		arg.ApiKeyID,
		arg.FromTime,
		arg.ToTime,
		arg.TopLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopUsageKeysRow
	for rows.Next() {
		var i ListTopUsageKeysRow
		if err := rows.Scan(
			&i.ApiKeyID,
			&i.EmployeeName,
			&i.KeyHint,
			&i.InputTokens,
			&i.OutputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageSummary = `-- name: ListUsageSummary :many
WITH summary AS (
    SELECT u.api_key_id, k.employee_name, k.key_hint, u.model,
        SUM(u.input_tokens)::bigint AS input_tokens,
        SUM(u.output_tokens)::bigint AS output_tokens,
        (SUM(u.input_tokens) + SUM(u.output_tokens))::bigint AS total_tokens
    FROM api_key_usage_daily u
    JOIN api_keys k ON k.id = u.api_key_id
    WHERE (NULLIF($5::text, '')::uuid IS NULL OR u.api_key_id = NULLIF($5::text, '')::uuid)
      AND ($6::timestamptz IS NULL OR u.usage_date >= $6::date)
      AND ($7::timestamptz IS NULL OR u.usage_date <= $7::date)
    GROUP BY u.api_key_id, k.employee_name, k.key_hint, u.model
)
SELECT api_key_id, employee_name, key_hint, model, input_tokens, output_tokens
FROM summary
WHERE $1::bigint IS NULL
   OR total_tokens < $1::bigint
   OR (total_tokens = $1::bigint AND api_key_id::text > $2::text)
   OR (total_tokens = $1::bigint AND api_key_id::text = $2::text AND model > $3::text)
ORDER BY total_tokens DESC, api_key_id, model
LIMIT $4
`

type ListUsageSummaryParams struct {
	AfterTotal  *int64
	AfterApiKey string
	AfterModel  string
	PageLimit   int32
	ApiKeyID    string
	FromTime    pgtype.Timestamptz
	ToTime      pgtype.Timestamptz
}

type ListUsageSummaryRow struct {
	ApiKeyID     string
	EmployeeName string
	KeyHint      string
	Model        string
	InputTokens  int64
	OutputTokens int64
}

func (q *Queries) ListUsageSummary(ctx context.Context, arg ListUsageSummaryParams) ([]ListUsageSummaryRow, error) {
	rows, err := q.db.Query(ctx, listUsageSummary,
		arg.AfterTotal,
		arg.AfterApiKey,
		arg.AfterModel,
		arg.PageLimit,
		arg.ApiKeyID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageSummaryRow
	for rows.Next() {
		var i ListUsageSummaryRow
		if err := rows.Scan(
			&i.ApiKeyID,
			&i.EmployeeName,
			&i.KeyHint,
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPoolAssignments = `-- name: LockPoolAssignments :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 731242002))
`

func (q *Queries) LockPoolAssignments(ctx context.Context, poolID string) error {
	_, err := q.db.Exec(ctx, lockPoolAssignments, poolID)
	return err
}

const lockPoolForUpdate = `-- name: LockPoolForUpdate :one
SELECT provider FROM pools WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPoolForUpdate(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockPoolForUpdate, id)
	var provider string
	err := row.Scan(&provider)
	return provider, err
}

const markPoolMixed = `-- name: MarkPoolMixed :exec
UPDATE pools SET provider = 'mixed', updated_at = now() WHERE id = $1
`

func (q *Queries) MarkPoolMixed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markPoolMixed, id)
	return err
}

const pinnedAPIKeyValid = `-- name: PinnedAPIKeyValid :one
SELECT EXISTS(
    SELECT 1 FROM api_keys
    WHERE key_hmac = $1
      AND pool_id = $2
      AND revoked_at IS NULL
      AND (expires_at IS NULL OR expires_at > now())
)
`

type PinnedAPIKeyValidParams struct {
	KeyHmac []byte
	PoolID  string
}

func (q *Queries) PinnedAPIKeyValid(ctx context.Context, arg PinnedAPIKeyValidParams) (bool, error) {
	row := q.db.QueryRow(ctx, pinnedAPIKeyValid, arg.KeyHmac, arg.PoolID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const providerAccountHasCapacity = `-- name: ProviderAccountHasCapacity :one
SELECT (
    SELECT count(*) FROM api_key_account_bindings b
    JOIN api_keys k ON k.id = b.api_key_id
    WHERE b.provider_account_id = $1
      AND k.revoked_at IS NULL
      AND (k.expires_at IS NULL OR k.expires_at > now())
) < settings.max_api_keys_per_account
FROM global_settings settings
WHERE settings.singleton
`

func (q *Queries) ProviderAccountHasCapacity(ctx context.Context, providerAccountID string) (bool, error) {
	row := q.db.QueryRow(ctx, providerAccountHasCapacity, providerAccountID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const reassignAPIKey = `-- name: ReassignAPIKey :exec
UPDATE api_key_account_bindings
SET provider_account_id = $1, assigned_at = now()
WHERE api_key_id = $2
`

type ReassignAPIKeyParams struct {
	ProviderAccountID string
	ApiKeyID          string
}

func (q *Queries) ReassignAPIKey(ctx context.Context, arg ReassignAPIKeyParams) error {
	_, err := q.db.Exec(ctx, reassignAPIKey, arg.ProviderAccountID, arg.ApiKeyID)
	return err
}

const recordRequestSuccess = `-- name: RecordRequestSuccess :exec
WITH account AS (
    UPDATE provider_accounts SET
        status = CASE WHEN status IN ('disabled', 'exhausted') THEN status ELSE 'active' END,
        cooldown_until = CASE WHEN status IN ('disabled', 'exhausted') THEN cooldown_until ELSE NULL END,
        last_success_at = $1,
        health_status = 'healthy',
        last_checked_at = $1,
        last_health_error_code = NULL,
        consecutive_health_failures = 0,
        updated_at = now()
    WHERE provider_accounts.id = $3
    RETURNING provider_accounts.id
)
UPDATE api_keys key
SET last_used_at = $1
WHERE key.id = $2 AND EXISTS(SELECT 1 FROM account)
`

type RecordRequestSuccessParams struct {
	OccurredAt pgtype.Timestamptz
	ApiKeyID   string
	AccountID  string
}

func (q *Queries) RecordRequestSuccess(ctx context.Context, arg RecordRequestSuccessParams) error {
	_, err := q.db.Exec(ctx, recordRequestSuccess, arg.OccurredAt, arg.ApiKeyID, arg.AccountID)
	return err
}

const resolveAPIKey = `-- name: ResolveAPIKey :one
SELECT
    k.id AS key_id, k.pool_id AS key_pool_id, k.employee_name, k.key_hint, k.scopes,
    k.rate_limit, k.expires_at AS key_expires_at, k.revoked_at, k.last_used_at,
    k.created_at AS key_created_at,
    p.id AS pool_id, p.name AS pool_name, p.provider AS pool_provider,
    p.created_at AS pool_created_at, p.updated_at AS pool_updated_at,
    a.id AS account_id, a.provider AS account_provider, a.credential_type,
    a.display_name, a.credential_ciphertext, a.credential_version, a.status,
    a.fast_mode_enabled, a.health_status, a.quota_snapshot, a.cooldown_until,
    a.last_success_at, a.last_failure_at, a.created_at AS account_created_at,
    a.updated_at AS account_updated_at, pa.enabled AS membership_enabled
FROM api_keys k
JOIN pools p ON p.id = k.pool_id
JOIN api_key_account_bindings b ON b.api_key_id = k.id
JOIN provider_accounts a ON a.id = b.provider_account_id
JOIN pool_accounts pa ON pa.pool_id = p.id AND pa.provider_account_id = a.id
WHERE k.key_hmac = $1
  AND k.revoked_at IS NULL
  AND (k.expires_at IS NULL OR k.expires_at > now())
`

type ResolveAPIKeyRow struct {
	KeyID                string
	KeyPoolID            string
	EmployeeName         string
	KeyHint              string
	Scopes               []string
	RateLimit            int32
	KeyExpiresAt         pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
	LastUsedAt           pgtype.Timestamptz
	KeyCreatedAt         pgtype.Timestamptz
	PoolID               string
	PoolName             string
	PoolProvider         string
	PoolCreatedAt        pgtype.Timestamptz
	PoolUpdatedAt        pgtype.Timestamptz
	AccountID            string
	AccountProvider      string
	CredentialType       string
	DisplayName          string
	CredentialCiphertext []byte
	CredentialVersion    int32
	Status               string
	FastModeEnabled      bool
	HealthStatus         string
	QuotaSnapshot        []byte
	CooldownUntil        pgtype.Timestamptz
	LastSuccessAt        pgtype.Timestamptz
	LastFailureAt        pgtype.Timestamptz
	AccountCreatedAt     pgtype.Timestamptz
	AccountUpdatedAt     pgtype.Timestamptz
	MembershipEnabled    bool
}

func (q *Queries) ResolveAPIKey(ctx context.Context, keyHmac []byte) (ResolveAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, resolveAPIKey, keyHmac)
	var i ResolveAPIKeyRow
	err := row.Scan(
		&i.KeyID,
		&i.KeyPoolID,
		&i.EmployeeName,
		&i.KeyHint,
		&i.Scopes,
		&i.RateLimit,
		&i.KeyExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.KeyCreatedAt,
		&i.PoolID,
		&i.PoolName,
		&i.PoolProvider,
		&i.PoolCreatedAt,
		&i.PoolUpdatedAt,
		&i.AccountID,
		&i.AccountProvider,
		&i.CredentialType,
		&i.DisplayName,
		&i.CredentialCiphertext,
		&i.CredentialVersion,
		&i.Status,
		&i.FastModeEnabled,
		&i.HealthStatus,
		&i.QuotaSnapshot,
		&i.CooldownUntil,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.AccountCreatedAt,
		&i.AccountUpdatedAt,
		&i.MembershipEnabled,
	)
	return i, err
}

const resolvePinnedAPIKey = `-- name: ResolvePinnedAPIKey :one
SELECT
    k.id AS key_id, k.pool_id AS key_pool_id, k.employee_name, k.key_hint, k.scopes,
    k.rate_limit, k.expires_at AS key_expires_at, k.revoked_at, k.last_used_at,
    k.created_at AS key_created_at,
    p.id AS pool_id, p.name AS pool_name, p.provider AS pool_provider,
    p.created_at AS pool_created_at, p.updated_at AS pool_updated_at,
    a.id AS account_id, a.provider AS account_provider, a.credential_type,
    a.display_name, a.credential_ciphertext, a.credential_version, a.status,
    a.fast_mode_enabled, a.health_status, a.quota_snapshot, a.cooldown_until,
    a.last_success_at, a.last_failure_at, a.created_at AS account_created_at,
    a.updated_at AS account_updated_at, pa.enabled AS membership_enabled
FROM api_keys k
JOIN pools p ON p.id = k.pool_id
JOIN pool_accounts pa ON pa.pool_id = p.id AND pa.provider_account_id = $1
JOIN provider_accounts a ON a.id = pa.provider_account_id
WHERE k.key_hmac = $2
  AND k.pool_id = $3
  AND k.revoked_at IS NULL
  AND (k.expires_at IS NULL OR k.expires_at > now())
`

type ResolvePinnedAPIKeyParams struct {
	AccountID string
	KeyHmac   []byte
	PoolID    string
}

type ResolvePinnedAPIKeyRow struct {
	KeyID                string
	KeyPoolID            string
	EmployeeName         string
	KeyHint              string
	Scopes               []string
	RateLimit            int32
	KeyExpiresAt         pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
	LastUsedAt           pgtype.Timestamptz
	KeyCreatedAt         pgtype.Timestamptz
	PoolID               string
	PoolName             string
	PoolProvider         string
	PoolCreatedAt        pgtype.Timestamptz
	PoolUpdatedAt        pgtype.Timestamptz
	AccountID            string
	AccountProvider      string
	CredentialType       string
	DisplayName          string
	CredentialCiphertext []byte
	CredentialVersion    int32
	Status               string
	FastModeEnabled      bool
	HealthStatus         string
	QuotaSnapshot        []byte
	CooldownUntil        pgtype.Timestamptz
	LastSuccessAt        pgtype.Timestamptz
	LastFailureAt        pgtype.Timestamptz
	AccountCreatedAt     pgtype.Timestamptz
	AccountUpdatedAt     pgtype.Timestamptz
	MembershipEnabled    bool
}

func (q *Queries) ResolvePinnedAPIKey(ctx context.Context, arg ResolvePinnedAPIKeyParams) (ResolvePinnedAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, resolvePinnedAPIKey, arg.AccountID, arg.KeyHmac, arg.PoolID)
	var i ResolvePinnedAPIKeyRow
	err := row.Scan(
		&i.KeyID,
		&i.KeyPoolID,
		&i.EmployeeName,
		&i.KeyHint,
		&i.Scopes,
		&i.RateLimit,
		&i.KeyExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.KeyCreatedAt,
		&i.PoolID,
		&i.PoolName,
		&i.PoolProvider,
		&i.PoolCreatedAt,
		&i.PoolUpdatedAt,
		&i.AccountID,
		&i.AccountProvider,
		&i.CredentialType,
		&i.DisplayName,
		&i.CredentialCiphertext,
		&i.CredentialVersion,
		&i.Status,
		&i.FastModeEnabled,
		&i.HealthStatus,
		&i.QuotaSnapshot,
		&i.CooldownUntil,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.AccountCreatedAt,
		&i.AccountUpdatedAt,
		&i.MembershipEnabled,
	)
	return i, err
}

const resolveSessionAccount = `-- name: ResolveSessionAccount :one
SELECT a.id, a.provider, a.credential_type, a.display_name, a.credential_ciphertext,
    a.credential_version, a.status, a.fast_mode_enabled, a.health_status,
    a.quota_snapshot, a.cooldown_until, a.last_success_at, a.last_failure_at,
    a.created_at, a.updated_at
FROM session_bindings s
JOIN provider_accounts a ON a.id = s.provider_account_id
JOIN pool_accounts pa ON pa.pool_id = s.pool_id
    AND pa.provider_account_id = a.id
    AND pa.enabled
WHERE s.api_key_id = $1
  AND s.session_hash = $2
  AND s.expires_at > now()
`

type ResolveSessionAccountParams struct {
	ApiKeyID    string
	SessionHash []byte
}

type ResolveSessionAccountRow struct {
	ID                   string
	Provider             string
	CredentialType       string
	DisplayName          string
	CredentialCiphertext []byte
	CredentialVersion    int32
	Status               string
	FastModeEnabled      bool
	HealthStatus         string
	QuotaSnapshot        []byte
	CooldownUntil        pgtype.Timestamptz
	LastSuccessAt        pgtype.Timestamptz
	LastFailureAt        pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) ResolveSessionAccount(ctx context.Context, arg ResolveSessionAccountParams) (ResolveSessionAccountRow, error) {
	row := q.db.QueryRow(ctx, resolveSessionAccount, arg.ApiKeyID, arg.SessionHash)
	var i ResolveSessionAccountRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.CredentialType,
		&i.DisplayName,
		&i.CredentialCiphertext,
		&i.CredentialVersion,
		&i.Status,
		&i.FastModeEnabled,
		&i.HealthStatus,
		&i.QuotaSnapshot,
		&i.CooldownUntil,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveSessionBinding = `-- name: SaveSessionBinding :exec
INSERT INTO session_bindings(api_key_id, pool_id, session_hash, provider_account_id, expires_at)
VALUES ($1, $2, $3,
    $4, $5)
ON CONFLICT(api_key_id, session_hash) DO UPDATE
SET expires_at = GREATEST(session_bindings.expires_at, excluded.expires_at)
WHERE session_bindings.provider_account_id = excluded.provider_account_id
`

type SaveSessionBindingParams struct {
	ApiKeyID          string
	PoolID            string
	SessionHash       []byte
	ProviderAccountID string
	ExpiresAt         pgtype.Timestamptz
}

func (q *Queries) SaveSessionBinding(ctx context.Context, arg SaveSessionBindingParams) error {
	_, err := q.db.Exec(ctx, saveSessionBinding,
		arg.ApiKeyID,
		arg.PoolID,
		arg.SessionHash,
		arg.ProviderAccountID,
		arg.ExpiresAt,
	)
	return err
}

const selectAccountForUpdate = `-- name: SelectAccountForUpdate :one
SELECT a.id
FROM provider_accounts a
JOIN pool_accounts pa ON pa.provider_account_id = a.id
    AND pa.pool_id = $1
    AND pa.enabled
CROSS JOIN global_settings settings
WHERE NOT (a.id::text = ANY(COALESCE($2::text[], ARRAY[]::text[])))
  AND (a.status = 'active' OR (a.status = 'cooling_down' AND a.cooldown_until <= now()))
  AND COALESCE(NULLIF(a.health_status, ''), 'unknown') != 'unhealthy'
  AND (SELECT count(*) FROM api_key_account_bindings b
      JOIN api_keys k ON k.id = b.api_key_id
      WHERE b.provider_account_id = a.id
        AND k.revoked_at IS NULL
        AND (k.expires_at IS NULL OR k.expires_at > now())) < settings.max_api_keys_per_account
ORDER BY pa.priority ASC,
    (SELECT count(*)::numeric / GREATEST(pa.weight, 1)
      FROM api_key_account_bindings b
      JOIN api_keys k ON k.id = b.api_key_id
      WHERE b.provider_account_id = a.id
        AND k.revoked_at IS NULL
        AND (k.expires_at IS NULL OR k.expires_at > now())) ASC,
    random()
FOR UPDATE OF a
LIMIT 1
`

type SelectAccountForUpdateParams struct {
	PoolID     string
	ExcludeIds []string
}

func (q *Queries) SelectAccountForUpdate(ctx context.Context, arg SelectAccountForUpdateParams) (string, error) {
	row := q.db.QueryRow(ctx, selectAccountForUpdate, arg.PoolID, arg.ExcludeIds)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateAPIKeyActivity = `-- name: UpdateAPIKeyActivity :exec
UPDATE api_keys
SET last_used_at = GREATEST(COALESCE(last_used_at, $1), $1)
WHERE id = $2
`

type UpdateAPIKeyActivityParams struct {
	OccurredAt pgtype.Timestamptz
	ID         string
}

func (q *Queries) UpdateAPIKeyActivity(ctx context.Context, arg UpdateAPIKeyActivityParams) error {
	_, err := q.db.Exec(ctx, updateAPIKeyActivity, arg.OccurredAt, arg.ID)
	return err
}

const updatePool = `-- name: UpdatePool :execrows
UPDATE pools
SET name = $1, updated_at = now()
WHERE id = $2
`

type UpdatePoolParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdatePool(ctx context.Context, arg UpdatePoolParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePool, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPoolAccount = `-- name: UpsertPoolAccount :execrows
INSERT INTO pool_accounts(pool_id, provider_account_id, weight, priority, enabled)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(pool_id, provider_account_id) DO UPDATE SET
    weight = excluded.weight,
    priority = excluded.priority,
    enabled = excluded.enabled
`

type UpsertPoolAccountParams struct {
	PoolID            string
	ProviderAccountID string
	Weight            int32
	Priority          int32
	Enabled           bool
}

func (q *Queries) UpsertPoolAccount(ctx context.Context, arg UpsertPoolAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertPoolAccount,
		arg.PoolID,
		arg.ProviderAccountID,
		arg.Weight,
		arg.Priority,
		arg.Enabled,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const writeAuditEvent = `-- name: WriteAuditEvent :exec
INSERT INTO audit_events(actor, action, target_type, target_id, result)
VALUES ($1, $2, $3, $4, $5)
`

type WriteAuditEventParams struct {
	Actor      string
	Action     string
	TargetType string
	TargetID   string
	Result     string
}

func (q *Queries) WriteAuditEvent(ctx context.Context, arg WriteAuditEventParams) error {
	_, err := q.db.Exec(ctx, writeAuditEvent,
		arg.Actor,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Result,
	)
	return err
}
