// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runtime.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminSessionActive = `-- name: AdminSessionActive :one
SELECT EXISTS(
    SELECT 1 FROM admin_sessions
    WHERE session_hash = $1
      AND revoked_at IS NULL
      AND expires_at > $2
)
`

type AdminSessionActiveParams struct {
	SessionHash []byte
	Now         pgtype.Timestamptz
}

func (q *Queries) AdminSessionActive(ctx context.Context, arg AdminSessionActiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, adminSessionActive, arg.SessionHash, arg.Now)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const allowAPIKeyRequest = `-- name: AllowAPIKeyRequest :one
INSERT INTO api_key_rate_limits(api_key_id, window_start, request_count)
VALUES ($1, date_trunc('minute', $2::timestamptz), 1)
ON CONFLICT(api_key_id) DO UPDATE SET
    window_start = CASE
        WHEN api_key_rate_limits.window_start < date_trunc('minute', $2::timestamptz)
            THEN date_trunc('minute', $2::timestamptz)
        ELSE api_key_rate_limits.window_start
    END,
    request_count = CASE
        WHEN api_key_rate_limits.window_start < date_trunc('minute', $2::timestamptz)
            THEN 1
        ELSE api_key_rate_limits.request_count + 1
    END
RETURNING request_count <= $3
`

type AllowAPIKeyRequestParams struct {
	ApiKeyID     string
	Now          pgtype.Timestamptz
	RequestLimit int32
}

func (q *Queries) AllowAPIKeyRequest(ctx context.Context, arg AllowAPIKeyRequestParams) (bool, error) {
	row := q.db.QueryRow(ctx, allowAPIKeyRequest, arg.ApiKeyID, arg.Now, arg.RequestLimit)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const clearAdminLoginFailures = `-- name: ClearAdminLoginFailures :exec
DELETE FROM admin_login_failures
WHERE scope_key = ANY($1::text[])
`

func (q *Queries) ClearAdminLoginFailures(ctx context.Context, scopeKeys []string) error {
	_, err := q.db.Exec(ctx, clearAdminLoginFailures, scopeKeys)
	return err
}

const createAdminSession = `-- name: CreateAdminSession :exec
INSERT INTO admin_sessions(session_hash, expires_at)
VALUES ($1, $2)
ON CONFLICT(session_hash) DO UPDATE
SET expires_at = excluded.expires_at, revoked_at = NULL
`

type CreateAdminSessionParams struct {
	SessionHash []byte
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) error {
	_, err := q.db.Exec(ctx, createAdminSession, arg.SessionHash, arg.ExpiresAt)
	return err
}

const getAdminLoginFailures = `-- name: GetAdminLoginFailures :one
SELECT failure_count, reset_at
FROM admin_login_failures
WHERE scope_key = $1
`

type GetAdminLoginFailuresRow struct {
	FailureCount int32
	ResetAt      pgtype.Timestamptz
}

func (q *Queries) GetAdminLoginFailures(ctx context.Context, scopeKey string) (GetAdminLoginFailuresRow, error) {
	row := q.db.QueryRow(ctx, getAdminLoginFailures, scopeKey)
	var i GetAdminLoginFailuresRow
	err := row.Scan(&i.FailureCount, &i.ResetAt)
	return i, err
}

const lockAdminLoginScope = `-- name: LockAdminLoginScope :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 731242003))
`

func (q *Queries) LockAdminLoginScope(ctx context.Context, scopeKey string) error {
	_, err := q.db.Exec(ctx, lockAdminLoginScope, scopeKey)
	return err
}

const recordAdminLoginFailure = `-- name: RecordAdminLoginFailure :exec
INSERT INTO admin_login_failures(scope_key, failure_count, reset_at)
VALUES ($1, 1, $2::timestamptz + interval '1 minute')
ON CONFLICT(scope_key) DO UPDATE SET
    failure_count = CASE
        WHEN admin_login_failures.reset_at <= $2::timestamptz THEN 1
        ELSE admin_login_failures.failure_count + 1
    END,
    reset_at = CASE
        WHEN admin_login_failures.reset_at <= $2::timestamptz THEN $2::timestamptz + interval '1 minute'
        ELSE admin_login_failures.reset_at
    END,
    updated_at = now()
`

type RecordAdminLoginFailureParams struct {
	ScopeKey string
	Now      pgtype.Timestamptz
}

func (q *Queries) RecordAdminLoginFailure(ctx context.Context, arg RecordAdminLoginFailureParams) error {
	_, err := q.db.Exec(ctx, recordAdminLoginFailure, arg.ScopeKey, arg.Now)
	return err
}

const revokeAdminSession = `-- name: RevokeAdminSession :exec
UPDATE admin_sessions
SET revoked_at = $1
WHERE session_hash = $2 AND revoked_at IS NULL
`

type RevokeAdminSessionParams struct {
	RevokedAt   pgtype.Timestamptz
	SessionHash []byte
}

func (q *Queries) RevokeAdminSession(ctx context.Context, arg RevokeAdminSessionParams) error {
	_, err := q.db.Exec(ctx, revokeAdminSession, arg.RevokedAt, arg.SessionHash)
	return err
}
